In [77]:
import numpy as np
import math
import random

In [78]:
# def generateKeyMatrix(n, modulo):
#     while True:
#         key_matrix = np.random.randint(1, modulo, size=(n, n))
#         try:
#             inverse_key_matrix = inverse(key_matrix, modulo)
#             return key_matrix, inverse_key_matrix
#         except ValueError:
#             continue  # Regenerate if not invertible

In [79]:
def generateKeyMatrix(n, modulo):
    while True:
        key_matrix = np.random.randint(0, modulo, size=(n, n))
        # Compute determinant mod
        a, b = key_matrix[0]
        c, d = key_matrix[1]
        det = (a*d - b*c) % modulo
        if math.gcd(det, modulo) == 1:
            try:
                inverse_key_matrix = inverse_2x2_mod(key_matrix, modulo)
                return key_matrix, inverse_key_matrix
            except ValueError:
                continue
        else:
            print("Failed Iteration")

In [80]:
def inverse_2x2_mod(matrix, modulo):
    # Compute modular inverse for a 2x2 matrix using integer arithmetic only
    a, b = matrix[0]
    c, d = matrix[1]
    det = int((a*d - b*c) % modulo)
    if math.gcd(det, modulo) != 1:
        raise ValueError("Matrix not invertible modulo {}".format(modulo))
    det_inv = pow(det, -1, modulo)
    # Adjugate matrix
    return (det_inv * np.array([[d, -b],
                                [-c, a]])) % modulo

In [81]:
def encrypt(plaintext, key_matrix, modulo, alphabet):
    # Map chars to numbers from 0 to len(alphabet)-1
    char_to_num = {char: idx for idx, char in enumerate(alphabet)}
    num_to_char = {v: k for k, v in char_to_num.items()}
    padding_val = len(alphabet)  # Use a padding value outside the char range
    # Convert plaintext to numbers
    numbers = [char_to_num[c] for c in plaintext if c in char_to_num]
    # Pad if necessary
    if len(numbers) % 2 != 0:
        numbers.append(padding_val)

    plaintext_matrix = np.array(numbers).reshape(-1, 2).T
    ciphertext_matrix = (key_matrix.dot(plaintext_matrix) % modulo).T
    # Convert back to chars (skip padding_val when converting back)
    ciphertext = []
    for pair in ciphertext_matrix:
        for num in pair:
            if num != padding_val:
                if num in num_to_char:
                    ciphertext.append(num_to_char[num])
                else:
                    # If something unexpected, place a placeholder
                    ciphertext.append('?')
    return ''.join(ciphertext), ciphertext_matrix

In [82]:
def decrypt(ciphertext, inverse_key_matrix, modulo, alphabet):
    char_to_num = {char: idx for idx, char in enumerate(alphabet)}
    num_to_char = {v: k for k, v in char_to_num.items()}
    padding_val = len(alphabet)

    numbers = [char_to_num[c] for c in ciphertext if c in char_to_num]
    if len(numbers) % 2 != 0:
        numbers.append(padding_val)

    cipher_matrix = np.array(numbers).reshape(-1, 2)
    decrypted_matrix = (inverse_key_matrix.dot(cipher_matrix.T) % modulo).T

    # Convert back to text and remove padding
    plaintext_chars = []
    for pair in decrypted_matrix:
        for num in pair:
            if num == padding_val:
                # Padding encountered, skip it
                continue
            if num in num_to_char:
                plaintext_chars.append(num_to_char[num])
            else:
                plaintext_chars.append('?')
    return ''.join(plaintext_chars)

In [83]:
# Define the alphabet, modulo, and key matrix
modulo = 59
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,'?&\n"
print("Alphabet Length:", len(alphabet))

key_matrix = np.array([
    [3, 2],
    [5, 7]
])

# Compute inverse key matrix dynamically
inverse_key_matrix = inverse_2x2_mod(key_matrix, modulo)

# Function to generate a random string of length l from the alphabet
def generate_random_string(alphabet, l):
    return ''.join(random.choice(alphabet) for _ in range(l))

# Encrypt and decrypt test
def test_encryption_decryption(l):
    plaintext = generate_random_string(alphabet, l)
    ciphertext, ciphertext_matrix = encrypt(plaintext, key_matrix, modulo, alphabet)
    decrypted_text = decrypt(ciphertext, inverse_key_matrix, modulo, alphabet)
    return plaintext, decrypted_text, plaintext == decrypted_text

# Run 50 tests
for idx in range(1, 51):
    plaintext, decrypted_text, result = test_encryption_decryption(200)  # Change 20 to desired string length
    if result:
        print(f"Test {idx}: True")
    else:
        print(f"Test {idx}: False")
        print(f"  Original: {plaintext}")
        print(f"  Decrypted: {decrypted_text}")

Alphabet Length: 59
Test 1: True
Test 2: True
Test 3: True
Test 4: True
Test 5: True
Test 6: True
Test 7: True
Test 8: True
Test 9: True
Test 10: True
Test 11: True
Test 12: True
Test 13: True
Test 14: True
Test 15: True
Test 16: True
Test 17: True
Test 18: True
Test 19: True
Test 20: True
Test 21: True
Test 22: True
Test 23: True
Test 24: True
Test 25: True
Test 26: True
Test 27: True
Test 28: True
Test 29: True
Test 30: True
Test 31: True
Test 32: True
Test 33: True
Test 34: True
Test 35: True
Test 36: True
Test 37: True
Test 38: True
Test 39: True
Test 40: True
Test 41: True
Test 42: True
Test 43: True
Test 44: True
Test 45: True
Test 46: True
Test 47: True
Test 48: True
Test 49: True
Test 50: True


In [122]:
modulo = 59  # Adjust modulo to match extended alphabet size
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,'?&\n"
print("Alphabet Length:", len(alphabet))
key_matrix = np.array([
    [3, 2],
    [5, 7]
])

print(len(alphabet))
plaintext = ("Hello My name is Nic")
# Compute inverse key matrix dynamically
inverse_key_matrix = inverse_2x2_mod(key_matrix, modulo)
print(f"Key Matrix:\n{key_matrix}")
print(f"Inverse Key Matrix:\n{inverse_key_matrix}")

# Encrypt the plaintext
ciphertext, ciphertext_matrix = encrypt(plaintext, key_matrix, modulo, alphabet)
print(f"Ciphertext Matrix:\n{ciphertext_matrix}")

# Decrypt the ciphertext
decrypted_text = decrypt(ciphertext, inverse_key_matrix, modulo, alphabet)
print("Original Text:", plaintext)
print(f"Ciphertext: {ciphertext}")
print(f"Decrypted Text: {decrypted_text}")
print(f"Condition: {np.linalg.cond(key_matrix)}")


Alphabet Length: 59
59
Key Matrix:
[[3 2]
 [5 7]]
Inverse Key Matrix:
[[ 6 32]
 [21 11]]
Ciphertext Matrix:
[[22  9]
 [ 8 31]
 [47 33]
 [18 56]
 [57  2]
 [36 42]
 [17 42]
 [13  6]
 [ 5 56]
 [40 12]]
Original Text: Hello My name is Nic
Ciphertext: WJIfvhS?&CkqRqNGF?oM
Decrypted Text: Hello My name is Nic
Condition: 7.780565547548909


In [118]:
modulo = 59  # Adjust modulo to match extended alphabet size
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,!&'\n"
print("Alphabet Length:", len(alphabet))
plaintext = """Hello My name is Nic Hello My name Hello My 
name Hello My name Hello My name Hello My name 
name Hello My name Hello My name Hello My name 
Ner gonna say gobyrsqd aqq Hello check xxxxxxxxxxxx ga zz ' 
"""
key_matrix = np.array([
    [3, 2],
    [5, 7]
])

# Compute inverse key matrix dynamically
inverse_key_matrix = inverse_2x2_mod(key_matrix, modulo)
print(f"Key Matrix:\n{key_matrix}")
print(f"Inverse Key Matrix:\n{inverse_key_matrix}")

# Encrypt the plaintext
ciphertext, ciphertext_matrix = encrypt(plaintext, key_matrix, modulo, alphabet)
print(f"Ciphertext Matrix:\n{ciphertext_matrix}")

# Decrypt the ciphertext
decrypted_text = decrypt(ciphertext, inverse_key_matrix, modulo, alphabet)
print("Original Text:", plaintext)
print()
print(f"Ciphertext: {ciphertext}")
print()
print(f"Decrypted Text: {decrypted_text}")
print()
print(f"Condition: {np.linalg.cond(key_matrix)}")

Alphabet Length: 59
Key Matrix:
[[3 2]
 [5 7]]
Inverse Key Matrix:
[[ 6 32]
 [21 11]]
Ciphertext Matrix:
[[22  9]
 [ 8 31]
 [47 33]
 [18 56]
 [57  2]
 [36 42]
 [17 42]
 [13  6]
 [ 5 56]
 [40 12]
 [52 14]
 [46 55]
 [14 52]
 [ 3 49]
 [18 24]
 [51 23]
 [56 46]
 [52 14]
 [46 55]
 [14 52]
 [ 3 49]
 [18 24]
 [16 32]
 [36 42]
 [17 42]
 [22  9]
 [ 8 31]
 [47 33]
 [18 56]
 [57  2]
 [36 42]
 [17 42]
 [22  9]
 [ 8 31]
 [47 33]
 [18 56]
 [57  2]
 [36 42]
 [17 42]
 [22  9]
 [ 8 31]
 [47 33]
 [18 56]
 [57  2]
 [36 42]
 [17 42]
 [16 32]
 [36 42]
 [17 42]
 [22  9]
 [ 8 31]
 [47 33]
 [18 56]
 [57  2]
 [36 42]
 [17 42]
 [22  9]
 [ 8 31]
 [47 33]
 [18 56]
 [57  2]
 [36 42]
 [17 42]
 [22  9]
 [ 8 31]
 [47 33]
 [18 56]
 [57  2]
 [36 42]
 [17 42]
 [23 27]
 [58 38]
 [43 12]
 [21  1]
 [51 23]
 [ 8 37]
 [ 1  8]
 [43 12]
 [56 35]
 [ 0 20]
 [39 42]
 [14 37]
 [44 11]
 [53 43]
 [22  9]
 [ 8 31]
 [47 33]
 [32 17]
 [28 51]
 [35 13]
 [ 9 57]
 [ 9 57]
 [ 9 57]
 [ 9 57]
 [ 9 57]
 [ 9 57]
 [43 12]
 [ 5 22]
 [19 22]
 [34

In [121]:
modulo = 59  # Adjust modulo to match extended alphabet size
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,!?'\n"
print("Alphabet Length:", len(alphabet))

plaintext = """
A full commitment's what I'm thinkin' of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching, but you're too shy to say it"""

key_matrix = np.array([
    [3, 2],
    [5, 7]
])

# Compute inverse key matrix dynamically
inverse_key_matrix = inverse_2x2_mod(key_matrix, modulo)
print(f"Key Matrix:\n{key_matrix}")
print(f"Inverse Key Matrix:\n{inverse_key_matrix}")

# Encrypt the plaintext
ciphertext, ciphertext_matrix = encrypt(plaintext, key_matrix, modulo, alphabet)
print(f"Ciphertext Matrix:\n{ciphertext_matrix}")

# Decrypt the ciphertext
decrypted_text = decrypt(ciphertext, inverse_key_matrix, modulo, alphabet)
print("Original Text:", plaintext)
print()
print(f"Ciphertext: {ciphertext}")
print()
print(f"Decrypted Text: {decrypted_text}")
print(f"Condition: {np.linalg.cond(key_matrix)}")


Alphabet Length: 59
Key Matrix:
[[3 2]
 [5 7]]
Inverse Key Matrix:
[[ 6 32]
 [21 11]]
Ciphertext Matrix:
[[56 54]
 [41  5]
 [35 17]
 [38 18]
 [46  7]
 [13 43]
 [15 13]
 [56 46]
 [30 38]
 [23  3]
 [16  6]
 [33 52]
 [ 3 58]
 [20 26]
 [41 23]
 [24 43]
 [ 3 30]
 [58  5]
 [54  4]
 [ 0  9]
 [32 30]
 [34 46]
 [ 6  4]
 [47 48]
 [35 17]
 [47  5]
 [25 10]
 [43 12]
 [ 3 52]
 [10 44]
 [49 49]
 [ 0 53]
 [ 2 43]
 [19 53]
 [31 29]
 [40 14]
 [ 0  9]
 [24 43]
 [58 38]
 [43 12]
 [ 2 49]
 [13 51]
 [49 33]
 [49  7]
 [ 3 58]
 [19  9]
 [18 55]
 [ 5 22]
 [18 22]
 [ 8 31]
 [20 20]
 [35 50]
 [45 19]
 [39  5]
 [54 21]
 [11 20]
 [41  5]
 [32  6]
 [ 2 10]
 [ 4  6]
 [ 9 37]
 [33 43]
 [10 53]
 [55 54]
 [32 28]
 [17 42]
 [53 58]
 [ 6  4]
 [39 31]
 [29  1]
 [40 51]
 [10 53]
 [57 44]
 [23 27]
 [ 7  7]
 [58 38]
 [43 12]
 [21  1]
 [51 23]
 [43 12]
 [19 27]
 [17 42]
 [53 58]
 [ 6  4]
 [43 45]
 [23 27]
 [ 7  7]
 [58 38]
 [43 12]
 [21  1]
 [51 23]
 [53 47]
 [ 3 52]
 [20 20]
 [35 50]
 [37 50]
 [39  5]
 [56 11]
 [40 39]
 [24

In [182]:
modulo = 59  # Adjust modulo to match extended alphabet size
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,'?&\n"
print("Alphabet Length:", len(alphabet))

plaintext = "Hello My name is Nic"
key_matrix, inverse_key_matrix = generateKeyMatrix(2, modulo)

# Compute inverse key matrix dynamically

print(f"Key Matrix:\n{key_matrix}")
print(f"Inverse Key Matrix:\n{inverse_key_matrix}")

# Encrypt the plaintext
ciphertext, ciphertext_matrix = encrypt(plaintext, key_matrix, modulo, alphabet)
print(f"Ciphertext Matrix:\n{ciphertext_matrix}")

# Decrypt the ciphertext
decrypted_text = decrypt(ciphertext, inverse_key_matrix, modulo, alphabet)
print("Original Text:", plaintext)
print(f"Ciphertext: {ciphertext}")
print(f"Decrypted Text: {decrypted_text}")
print(f"Condition: {np.linalg.cond(key_matrix)}")

#error at 2.0593548505965185, 5.945736302449729, 8.852726727607553

Alphabet Length: 59
Key Matrix:
[[53 21]
 [29 49]]
Inverse Key Matrix:
[[53 11]
 [18 20]]
Ciphertext Matrix:
[[57 21]
 [24 54]
 [26 50]
 [34 25]
 [35 56]
 [52 20]
 [27 55]
 [12 15]
 [20 21]
 [30 57]]
Original Text: Hello My name is Nic
Ciphertext: &VY,ayiZj? Ub'MPUVe&
Decrypted Text: Hello My name is Nic
Condition: 2.923542815739946


In [184]:

modulo = 59  # Adjust modulo to match extended alphabet size
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,'?&\n"
print("Alphabet Length:", len(alphabet))

plaintext = """
A full commitment's what I'm thinkin' of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching, but you're too shy to say it
Inside, we both know what's been going on
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down"""

key_matrix, inverse_key_matrix = generateKeyMatrix(2, modulo)

# Compute inverse key matrix dynamically

print(f"Key Matrix:\n{key_matrix}")
print(f"Inverse Key Matrix:\n{inverse_key_matrix}")

# Encrypt the plaintext
ciphertext, ciphertext_matrix = encrypt(plaintext, key_matrix, modulo, alphabet)
print(f"Ciphertext Matrix:\n{ciphertext_matrix}")

# Decrypt the ciphertext
decrypted_text = decrypt(ciphertext, inverse_key_matrix, modulo, alphabet)
print("Original Text:", plaintext)
print()
print(f"Ciphertext: {ciphertext}")
print()
print(f"Decrypted Text: {decrypted_text}")
print()
print(f"Condition: {np.linalg.cond(key_matrix)}")

Alphabet Length: 59
Key Matrix:
[[47 23]
 [48 47]]
Inverse Key Matrix:
[[45 42]
 [ 3 45]]
Ciphertext Matrix:
[[12 11]
 [30  0]
 [ 4 53]
 [44 31]
 [53 38]
 [ 5 11]
 [37 30]
 [57 48]
 [36 34]
 [57 47]
 [ 8 32]
 [25 33]
 [ 7  2]
 [48 19]
 [32 20]
 [42 53]
 [17 43]
 [55 22]
 [30 32]
 [ 1 10]
 [18 25]
 [42 23]
 [54 50]
 [49 54]
 [ 4 53]
 [18 39]
 [21 35]
 [53 47]
 [26 15]
 [57  9]
 [32 55]
 [19 13]
 [27 28]
 [40 48]
 [33  1]
 [33 33]
 [ 1 10]
 [42 53]
 [39 39]
 [53 47]
 [ 8 15]
 [19 33]
 [ 4 11]
 [47 28]
 [ 7  2]
 [22 45]
 [16 47]
 [58 34]
 [32 30]
 [53 34]
 [54  8]
 [47 11]
 [17 35]
 [34 46]
 [32 40]
 [37  1]
 [30  0]
 [35 18]
 [43 11]
 [32 13]
 [32 57]
 [24 23]
 [58 19]
 [14 34]
 [44 49]
 [10 49]
 [25 32]
 [54 50]
 [50 29]
 [47 29]
 [24  2]
 [58 19]
 [22 49]
 [16 32]
 [13 50]
 [39 39]
 [53 47]
 [ 4 36]
 [12 26]
 [53 47]
 [24  6]
 [10 49]
 [25 32]
 [54 50]
 [37  5]
 [16 32]
 [13 50]
 [39 39]
 [53 47]
 [ 4 36]
 [12 26]
 [50 46]
 [26 15]
 [54  8]
 [47 11]
 [43 24]
 [34 46]
 [40 55]
 [ 3 28]


In [89]:
def inverse_nxn_mod(matrix, modulo):
    # Convert to integers and work on a copy
    A = np.array(matrix, dtype=int) % modulo
    n = A.shape[0]

    # Create identity matrix
    I = np.eye(n, dtype=int)

    # Perform Gaussian elimination
    for i in range(n):
        # Find pivot (row with non-zero element in column i)
        for r in range(i, n):
            if A[r, i] % modulo != 0:
                # Swap pivot row if necessary
                if r != i:
                    A[[i, r]] = A[[r, i]]
                    I[[i, r]] = I[[r, i]]
                break
        else:
            # No pivot found, matrix not invertible
            raise ValueError("Matrix not invertible modulo {}".format(modulo))

        # Normalize pivot row
        inv_pivot = pow(int(A[i, i]), -1, modulo)
        A[i] = (A[i] * inv_pivot) % modulo
        I[i] = (I[i] * inv_pivot) % modulo

        # Eliminate other rows
        for r in range(n):
            if r != i:
                factor = A[r, i] % modulo
                if factor != 0:
                    A[r] = (A[r] - factor * A[i]) % modulo
                    I[r] = (I[r] - factor * I[i]) % modulo

    return I % modulo

In [90]:
def generateKeyMatrix_nxn(n, modulo):
    while True:
        key_matrix = np.random.randint(0, modulo, size=(n, n))
        # Compute determinant mod
        det = int(round(np.linalg.det(key_matrix))) % modulo
        if math.gcd(det, modulo) == 1:
            try:
                inverse_key_matrix = inverse_nxn_mod(key_matrix, modulo)
                return key_matrix, inverse_key_matrix
            except ValueError:
                continue
        else:
            # Not invertible, try again
            pass

In [91]:
def encryptNN(plaintext, key_matrix, modulo, alphabet):
    # Map chars to numbers from 0 to len(alphabet)-1
    n = key_matrix.shape[0]
    char_to_num = {char: idx for idx, char in enumerate(alphabet)}
    num_to_char = {v: k for k, v in char_to_num.items()}
    padding_val = len(alphabet)  # Use a padding value outside the char range
    # Convert plaintext to numbers
    numbers = [char_to_num[c] for c in plaintext if c in char_to_num]
    # Pad if necessary
    remainder = len(numbers) % n
    if remainder != 0:
        numbers.extend([padding_val] * (n - remainder))

    plaintext_matrix = np.array(numbers).reshape(-1, n).T
    ciphertext_matrix = (key_matrix.dot(plaintext_matrix) % modulo).T
    # Convert back to chars (skip padding_val when converting back)
    ciphertext = []
    for pair in ciphertext_matrix:
        for num in pair:
            if num != padding_val:
                if num in num_to_char:
                    ciphertext.append(num_to_char[num])
                else:
                    # If something unexpected, place a placeholder
                    ciphertext.append('?')
    return ''.join(ciphertext), ciphertext_matrix

In [92]:
def decryptNN(ciphertext, inverse_key_matrix, modulo, alphabet):
    n = inverse_key_matrix.shape[0]
    char_to_num = {char: idx for idx, char in enumerate(alphabet)}
    num_to_char = {v: k for k, v in char_to_num.items()}
    padding_val = len(alphabet)

    numbers = [char_to_num[c] for c in ciphertext if c in char_to_num]
    remainder = len(numbers) % n
    if remainder != 0:
        numbers.extend([padding_val] * (n - remainder))

    cipher_matrix = np.array(numbers).reshape(-1, n)
    decrypted_matrix = (inverse_key_matrix.dot(cipher_matrix.T) % modulo).T

    # Convert back to text and remove padding
    plaintext_chars = []
    for pair in decrypted_matrix:
        for num in pair:
            if num == padding_val:
                # Padding encountered, skip it
                continue
            if num in num_to_char:
                plaintext_chars.append(num_to_char[num])
            else:
                plaintext_chars.append('?')
    dec = ''.join(plaintext_chars)
    return dec.rstrip('A')

In [93]:

# Define the alphabet, modulo, and key matrix
modulo = 59
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,'?&\n"
print("Alphabet Length:", len(alphabet))
keyMatrixSize = 3

key_matrix, inverse_key_matrix = generateKeyMatrix_nxn(keyMatrixSize, modulo)

# Function to generate a random string of length l from the alphabet
def generate_random_string(alphabet, l):
    while True:
        generated = ''.join(random.choice(alphabet) for _ in range(l))
        if generated[-1] != 'A':  # Ensure the string does not end with 'A'
            return generated

# Encrypt and decrypt test
def test_encryption_decryption(l):
    plaintext = generate_random_string(alphabet, l)
    ciphertext, ciphertext_matrix = encryptNN(plaintext, key_matrix, modulo, alphabet)
    decrypted_text = decryptNN(ciphertext, inverse_key_matrix, modulo, alphabet)

    # Count trailing 'A' characters in the decrypted text
    trailing_a_count = len(decrypted_text) - len(decrypted_text.rstrip('A'))

    return plaintext, decrypted_text, trailing_a_count, plaintext == decrypted_text

stringLength = 99
testLength = 10
correct = 0
decryptedTextLength = 0
# Run 50 tests
for idx in range(1, testLength + 1):
    plaintext, decrypted_text, trailing_a_count, result = test_encryption_decryption(stringLength)
    decryptedTextLength = len(decrypted_text)
    if result:
        print(f"Test {idx}: True")
        correct += 1
    else:
        print(f"Test {idx}: False")
        print(f"  Original: {plaintext}")
        print(f" Decrypted: {decrypted_text}")
    print(f" Trailing 'A' count: {trailing_a_count}")

print()
print(f"Correct: {correct}/{testLength}")
print("Plain Text Length: ", stringLength)
print("Key matrix Size  : ", keyMatrixSize)
print("Alphabet Length  : ", len(alphabet))
print(f"Plain Text Length / {keyMatrixSize}: ", stringLength/keyMatrixSize)
print(f"Plain Text Length % {keyMatrixSize}: ", stringLength%keyMatrixSize)
print(f"Plain Text Length % 59: ", stringLength%59)
print(f"Test Plaintext Length % 59 - Length %{keyMatrixSize}: ", stringLength%59 - stringLength%keyMatrixSize)
print("TEST stringLength % keyMatrixSize: ", stringLength%keyMatrixSize)
print("TEST keyMatrixSize - stringLength % keyMatrixSize: ", keyMatrixSize - stringLength%keyMatrixSize)

print()
print(f"Correct: {correct}/{testLength}")
print("decrypted  Length: ", decryptedTextLength)
print("Key matrix Size  : ", keyMatrixSize)
print("Alphabet Length  : ", len(alphabet))
print(f"decrypted Length / {keyMatrixSize}: ", decryptedTextLength/keyMatrixSize)
print(f"decrypted Length % {keyMatrixSize}: ", decryptedTextLength%keyMatrixSize)
print(f"decrypted Length % 59: ", decryptedTextLength%59)
print(f"Test decrypted Length % 59 - Length %{keyMatrixSize}: ", decryptedTextLength%59 - decryptedTextLength%keyMatrixSize)
print("TEST decrypted % keyMatrixSize: ", decryptedTextLength%keyMatrixSize)
print("TEST keyMatrixSize - decrypted % keyMatrixSize: ", keyMatrixSize - decryptedTextLength%keyMatrixSize)



Alphabet Length: 59
Test 1: True
 Trailing 'A' count: 0
Test 2: True
 Trailing 'A' count: 0
Test 3: True
 Trailing 'A' count: 0
Test 4: True
 Trailing 'A' count: 0
Test 5: True
 Trailing 'A' count: 0
Test 6: True
 Trailing 'A' count: 0
Test 7: True
 Trailing 'A' count: 0
Test 8: True
 Trailing 'A' count: 0
Test 9: True
 Trailing 'A' count: 0
Test 10: True
 Trailing 'A' count: 0

Correct: 10/10
Plain Text Length:  99
Key matrix Size  :  3
Alphabet Length  :  59
Plain Text Length / 3:  33.0
Plain Text Length % 3:  0
Plain Text Length % 59:  40
Test Plaintext Length % 59 - Length %3:  40
TEST stringLength % keyMatrixSize:  0
TEST keyMatrixSize - stringLength % keyMatrixSize:  3

Correct: 10/10
decrypted  Length:  99
Key matrix Size  :  3
Alphabet Length  :  59
decrypted Length / 3:  33.0
decrypted Length % 3:  0
decrypted Length % 59:  40
Test decrypted Length % 59 - Length %3:  40
TEST decrypted % keyMatrixSize:  0
TEST keyMatrixSize - decrypted % keyMatrixSize:  3


In [94]:
modulo = 59  # Adjust modulo to match extended alphabet size
keyMatrixSize = 2
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,!'?\n"
print("Alphabet Length:", len(alphabet))

plaintext = "Hello My name is Nic"
key_matrix, inverse_key_matrix = generateKeyMatrix_nxn(keyMatrixSize, modulo)
# Compute inverse key matrix dynamically

print(f"Key Matrix:\n{key_matrix}")
print(f"Inverse Key Matrix:\n{inverse_key_matrix}")

# Encrypt the plaintext
ciphertext, ciphertext_matrix = encrypt(plaintext, key_matrix, modulo, alphabet)

# Decrypt the ciphertext
decrypted_text = decrypt(ciphertext, inverse_key_matrix, modulo, alphabet)
print("Original Text:", plaintext)
print(f"Ciphertext: {ciphertext}")
print(f"Decrypted Text: {decrypted_text}")

Alphabet Length: 59
Key Matrix:
[[29 14]
 [ 7 30]]
Inverse Key Matrix:
[[ 6  9]
 [34 53]]
Original Text: Hello My name is Nic
Ciphertext: hF?MALtywAvYFAJYmuVQ
Decrypted Text: Hello My name is Nic


In [95]:
modulo = 59  # Adjust modulo to match extended alphabet size\
keyMatrixSize = 6
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,!?'\n"
print("Alphabet Length:", len(alphabet))

plaintext = "Hello My name is Nic"
key_matrix, inverse_key_matrix = generateKeyMatrix_nxn(keyMatrixSize, modulo)

# Compute inverse key matrix dynamically


# Encrypt the plaintext
ciphertext, ciphertext_matrix = encryptNN(plaintext, key_matrix, modulo, alphabet)
print("Plain Text Length:", len(plaintext))
print("Ciphertext Length:", len(ciphertext))

print(f"Key Matrix:\n{key_matrix}")
print(f"Inverse Key Matrix:\n{inverse_key_matrix}")
# Decrypt the ciphertext
decrypted_text = decryptNN(ciphertext, inverse_key_matrix, modulo, alphabet)
print("Original Text:", plaintext)
print(f"Ciphertext: {ciphertext}")
print(f"Decrypted Text: {decrypted_text}")

Alphabet Length: 59
Plain Text Length: 20
Ciphertext Length: 24
Key Matrix:
[[14 42  7 31  3 58]
 [44 28  0 16 34 37]
 [52  5 14 17 19 37]
 [30 29 40  5 53 21]
 [18 11 50 20  3 23]
 [32  1  8 26 28 11]]
Inverse Key Matrix:
[[29  0 31 15 23  4]
 [50  9 44 11 31 14]
 [39 13  7 13 40 37]
 [58 25 15 45 32 29]
 [42  4 47 22 16 25]
 [41 17 46 41 53 48]]
Original Text: Hello My name is Nic
Ciphertext: AJm'!SuEjHYBqGd!RPAmUDj,
Decrypted Text: Hello My name is Nic


In [96]:
lyrics = '''
We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinkin' of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching, but you're too shy to say it
Inside, we both know what's been going on
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching, but you're too shy to say it
Inside, we both know what's been going on
We know the game and we're gonna play it
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
'''

In [97]:
modulo = 59
keyMatrixSize = 20
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,'?&\n"
print("Alphabet Length:", len(alphabet))

# plaintext = lyrics.replace("\n", " ")
plaintext = lyrics
key_matrix, inverse_key_matrix = generateKeyMatrix_nxn(keyMatrixSize, modulo)
print()


# Compute inverse key matrix dynamically
print(f"Key Matrix:\n{key_matrix}")
print(f"Inverse Key Matrix:\n{inverse_key_matrix}")

# Encrypt the plaintext
ciphertext, ciphertext_matrix = encryptNN(plaintext, key_matrix, modulo, alphabet)

# Decrypt the ciphertext
decrypted_text = decryptNN(ciphertext, inverse_key_matrix, modulo, alphabet)
print("Original Text:", plaintext)
print()
print(f"Ciphertext: {ciphertext}")
print()
print(f"Decrypted Text: {decrypted_text}")

Alphabet Length: 59

Key Matrix:
[[42 42 20 41  4  3 46 32 37 55  5 29 55 55 21 31 33 24 58 54]
 [16  4 23 34 57 48 15 31  3 36 34 22 34 32 56 57 33  5  2 14]
 [38 41 20  4 31  2 20 49 51 48 40  4 43 24 30 35 30  3  0 12]
 [ 7 55 36  3 35 24 16  3 35 34 57 31 17 18 27 52 27  6 44  5]
 [28 14 21 28 29 36 22 15 39 51 54 24  0 45 51 47 23 38 55 54]
 [ 4  0 14 32 25 56 45 43  9 35 14 55 47  4 19 58 18  1 48  3]
 [34  6 23 22 11 46 16 27 53 10  2 28 32 42 25  5 40 40 36 19]
 [55 43 56 30  1 51 11 52 53 56 50 10 30 34 20 40 28  3 14 32]
 [ 0 37 33 53 16 50  3  2 44 36 16 12 37 32 32 22  5 12 42 18]
 [26 22 57 35 53 26 35 53  6 27  8 14 55 50 47 55 48 46 39  0]
 [ 3 39  1 29 44 31 46 29 30  9 19  3 53  5 56 51 31 26  3 54]
 [35 26 10  2 53 50 38 21 20 58 23 36 13 49 32 29 52 33 38 56]
 [43 41 15 11  7 35 24 20 43 15 34 46 42 58 58 10 11  5  9 56]
 [43 22 38 50 31  2 49 25 37 36 34 18 34 43 54 37 51 36 27 16]
 [42  7 32 26  5 36 30 32 38  8 23 36  5 12 13 19 45 32 53 33]
 [ 5 36 30 11 37 49 35