In [48]:
import numpy as np
from math import gcd
import sympy as sp

In [49]:
def generateKeyMatrix(n, modulo):
    while True:
        key_matrix = np.random.randint(1, modulo, size=(n, n))
        try:
            inverse_key_matrix = inverse(key_matrix, modulo)
            return key_matrix, inverse_key_matrix
        except ValueError:
            continue  # Regenerate if not invertible

In [50]:
def inverse(matrix, modulo):
    det = int(round(np.linalg.det(matrix))) % modulo
    det_inv = pow(det, -1, modulo)  # Modular inverse of determinant
    adjugate = np.round(np.linalg.inv(matrix) * det).astype(int) % modulo
    return (det_inv * adjugate) % modulo

In [52]:
def encrypt(plaintext, key_matrix, modulo, alphabet):
    # Map characters to numbers
    char_to_num = {char: idx + 1 for idx, char in enumerate(alphabet)}
    num_to_char = {v: k for k, v in char_to_num.items()}

    # Convert plaintext to numbers and pair into groups
    numbers = [char_to_num[char] for char in plaintext if char in char_to_num]
    if len(numbers) % 2 != 0:
        numbers.append(0)  # Padding if necessary

    plaintext_matrix = np.array(numbers).reshape(-1, 2).T
    print("Original Matrix: \n", np.array(numbers).reshape(-1, 2))
    ciphertext_matrix = (np.dot(key_matrix, plaintext_matrix) % modulo).T

    # Convert numbers back to characters
    ciphertext = ''.join(num_to_char.get(num, '') for pair in ciphertext_matrix for num in pair if num != 0)
    return ciphertext, ciphertext_matrix

In [53]:
def decrypt(ciphertext, inverse_key_matrix, modulo, alphabet):
    # Map numbers back to plaintext
    char_to_num = {char: idx + 1 for idx, char in enumerate(alphabet)}
    num_to_char = {v: k for k, v in char_to_num.items()}

    numbers = [char_to_num[char] for char in ciphertext if char in char_to_num]
    if len(numbers) % 2 != 0:
        numbers.append(0)  # Padding if necessary

    cipher_matrix = np.array(numbers).reshape(-1, 2)

    decrypted_matrix = (np.dot(inverse_key_matrix, cipher_matrix.T) % modulo).T
    text = ''.join(num_to_char.get(int(round(num)), '') for pair in decrypted_matrix for num in pair if num != 0)
    return text

In [54]:
modulo = 54  # Adjust modulo to match extended alphabet size
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,!?"

plaintext = "Hello My name is Nic"
key_matrix = np.array([[3, 2], [5, 7]])

# Compute inverse key matrix dynamically
inverse_key_matrix = inverse(key_matrix, modulo)
print(f"Key Matrix:\n{key_matrix}")
print(f"Inverse Key Matrix:\n{inverse_key_matrix}")

# Encrypt the plaintext
ciphertext, ciphertext_matrix = encrypt(plaintext, key_matrix, modulo, alphabet)
print(f"Ciphertext Matrix:\n{ciphertext_matrix}")

# Decrypt the ciphertext
decrypted_text = decrypt(ciphertext, inverse_key_matrix, modulo, alphabet)
print("Original Text:", plaintext)
print(f"Ciphertext: {ciphertext}")
print(f"Decrypted Text: {decrypted_text}")

ciphertext, ciphertext_matrix = encrypt(plaintext, inverse_key_matrix, modulo, alphabet)
decrypted_text = decrypt(ciphertext, key_matrix, modulo, alphabet)
print(f"Ciphertext: {ciphertext}")
print(f"Decrypted Text: {decrypted_text}")

Key Matrix:
[[3 2]
 [5 7]]
Inverse Key Matrix:
[[35 29]
 [44 15]]
Original Matrix: 
 [[ 8 31]
 [38 38]
 [41 53]
 [13 51]
 [53 40]
 [27 39]
 [31 53]
 [35 45]
 [53 14]
 [35 29]]
Ciphertext Matrix:
[[32 41]
 [28 24]
 [13 36]
 [33 44]
 [23  5]
 [51 30]
 [37 40]
 [33  4]
 [25 39]
 [ 1  0]]
Original Text: Hello My name is Nic
Ciphertext: fobXMjgrWEydkngDYmA
Decrypted Text: oYBZofAFfGIvYNcHKir
Original Matrix: 
 [[ 8 31]
 [38 38]
 [41 53]
 [13 51]
 [53 40]
 [27 39]
 [31 53]
 [35 45]
 [53 14]
 [35 29]]
Ciphertext: sGBbBGrosPXsd tAuDNe
Decrypted Text: oDHrTEzUEMChifUouxQ


In [55]:
modulo = 54  # Adjust modulo to match extended alphabet size
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,!?"

plaintext = "Hello My name is Nic"
key_matrix, inverse_key_matrix = generateKeyMatrix(2, 54)

# Compute inverse key matrix dynamically

print(f"Key Matrix:\n{key_matrix}")
print(f"Inverse Key Matrix:\n{inverse_key_matrix}")

# Encrypt the plaintext
ciphertext, ciphertext_matrix = encrypt(plaintext, key_matrix, modulo, alphabet)
print(f"Ciphertext Matrix:\n{ciphertext_matrix}")

# Decrypt the ciphertext
decrypted_text = decrypt(ciphertext, inverse_key_matrix, modulo, alphabet)
print("Original Text:", plaintext)
print(f"Ciphertext: {ciphertext}")
print(f"Decrypted Text: {decrypted_text}")

ciphertext, ciphertext_matrix = encrypt(plaintext, inverse_key_matrix, modulo, alphabet)
decrypted_text = decrypt(ciphertext, key_matrix, modulo, alphabet)
print(f"Ciphertext: {ciphertext}")
print(f"Decrypted Text: {decrypted_text}")

Key Matrix:
[[27 29]
 [ 4 13]]
Inverse Key Matrix:
[[49 14]
 [ 7 27]]
Original Matrix: 
 [[ 8 31]
 [38 38]
 [41 53]
 [13 51]
 [53 40]
 [27 39]
 [31 53]
 [35 45]
 [53 14]
 [35 29]]
Ciphertext Matrix:
[[35  3]
 [22 52]
 [52 43]
 [48 13]
 [53 30]
 [24 21]
 [52  3]
 [36 23]
 [ 1 16]
 [ 4 31]]
Original Text: Hello My name is Nic
Ciphertext: iCVzzqvM dXUzCjWAPDe
Decrypted Text: cBXtRMxmuuLgzMhICGjA
Original Matrix: 
 [[ 8 31]
 [38 38]
 [41 53]
 [13 51]
 [53 40]
 [27 39]
 [31 53]
 [35 45]
 [53 14]
 [35 29]]
Ciphertext: PcRxyrAJYugubWBmuOB
Decrypted Text: eItTGTuZnInoSgycdEH
